### ISSUE TITLE
[React Native + Babel issues] depencency issues

### ISSUE THREAD

**Issue by oreqizer** [chrisbateman/webpack-visualizer#10]
I'm using the plugin together with newest React Native, React 15 and Babel 6. Since your plugin uses Babel 5 and older version of React, it causes some collisions (npm 3). Updating them manually solves the issue for me.

**Comment by chrisbateman** [comment]
@oreqizer Babel is a devDependency, so that shouldn't be installed when you install the plugin. I also don't think that npm 3 also should have any issues with multiple versions of React. Can you add some specifics about what conflict is happening there?

**Comment by chrisbateman** [comment]
Closing for now. Feel free to reopen if you can provide some more info.
