### ISSUE TITLE
Writing stats file fails if path doesn't exist

### ISSUE THREAD

**Issue by ludekstepan** [chrisbateman/webpack-visualizer#24]
Since stats.html is no longer a Webpack asset (https://github.com/chrisbateman/webpack-visualizer/commit/1dae9849ab5ae85da85f6b394d346e163078a9fd) The plugin fails to write the file if the directory doesn't exist, for example if configured to write the file to some other directory then `./dist/`. Prior to the change above, Webpack took the responsibility of creating the directories.

Now, the plugin fails with error:
`webpack-visualizer-plugin: error writing stats file`

**Comment by chrisbateman** [comment]
Oops, sorry about that!

**Comment by ludekstepan** [comment]
Now, it works like a charm! Thanks!

**Comment by edouard-lopez** [comment]
Still got this on `"webpack-visualizer-plugin": "^0.1.10"` with

    new Visualizer({filename: './statistics.html'})

Without the `filename` option I got no error but no `stats.html` in my project directory either.
