### ISSUE TITLE
Web version not working, no results displayed

### ISSUE THREAD

**Issue by mkvlrn-cm42** [chrisbateman/webpack-visualizer#43]
Using webpack 3.3.0, so perhaps that's the issue? stats.json [here](https://gist.github.com/mikevaleriano/ae928cfe8d13f8340653bb0bb196af9d#file-gistfile1-txt)

**Comment by mkvlrn-cm42** [comment]
Working fine with updated webpack version 3.4.1, probably a stats.json issue.

**Comment by sungwoncho** [comment]
I can confirm that the web version does not work with webpack version `3.5.3`.

Related: https://github.com/chrisbateman/webpack-visualizer/issues/44
