### ISSUE TITLE
Add support for multiple entry points

### ISSUE THREAD

**Issue by avindra** [chrisbateman/webpack-visualizer#5]
I didn't see a way to visualize multiple entry points. The graph shows everything combined. It would be great if we could see separate endpoints for those with multi-page / single-page mixes.

**Comment by chrisbateman** [comment]
@avindra - would you happen to have a stats.json file you could share that demonstrates multiple entry points?

**Comment by nathanwelch** [comment]
@chrisbateman I could share one with you directly or give you my code for splitting up a stats.json by the filename of each chunk if you're interested. I was going to add this feature and do a PR but I couldn't easily get the app to run locally (I did not try using it as a plugin, only running the server locally). So, if you could give me some build steps for it along with any relevant environment config, node version, etc. you use, I could just do the PR for this.

I ended up just writing that function to split up my stats.json by chunk and then loaded the files individually on your live version of the app. Even with that extra step it was extremely useful. Thanks!

**Comment by kcjonson** [comment]
> I ended up just writing that function to split up my stats.json by chunk and then loaded the files individually on your live version of the app. Even with that extra step it was extremely useful. Thanks!

I'm particularly interested in only inspecting what made it into our common js and css bundles that were produced by the commons chunk plugin.

**Comment by ngbrown** [comment]
I think the most forward way would be to start with the list of `"chunks"` in `stats.json`, and then re-run the `buildHierarchy()` for all and then each chunk id, only including the size if the module is in the passed chunk.

At the end you would have N+1 hierarchies, with 'N' the number of chunks.  A selection (dropdown or radio-buttons) could then be shown to select "All" or each individual chunk.

**Comment by damianobarbati** [comment]
any news on this? multiple entrypoints support would be great!

**Comment by crabmusket** [comment]
This appears to be working! I just added this plugin to a project with two entry points, and I'm given a dropdown selector above the sunburst chart which lets me pick whether to view all chunks, or either of my entry points.

**Comment by avindra** [comment]
> This appears to be working!

Thats great to hear! maybe i'll get a chance to test it myself one day. closing for now :v:
