### ISSUE TITLE
Post CSS is throwing off numbers

### ISSUE THREAD

**Issue by manojkumarm** [chrisbateman/webpack-visualizer#9]
We have recently started using PostCSS with our web-pack build and noticed that even though the output css files are more or less the same size; the visualizer is reporting larger sizes in the pie chart; maybe I don't fully understand the visualization generated but just want to bring this to your attention.

I know this information is a bit scarce; but if you need any information to help debug I will be glad to provide the same.

thank you very much for this project; it is very helpful

**Comment by chrisbateman** [comment]
@manojkumarm  This tool only reports pre-minified sizes - not sure if that's all it is in this case. If you think there's more to it, could you maybe send me a stats.json file that demonstrates the issue?

**Comment by chrisbateman** [comment]
I'm hoping that the fix for #17 solved this as well. If not - please reopen and add a demo stats.json file.
